### ISSUE TITLE
How to use Sinopia for caching only?

### ISSUE THREAD

**Issue by goloroden** [rlidwka/sinopia#175]
I'd like to use Sinopia to cache downloaded modules when I run `npm install <module>`. AFAICS this is quite easy to setup.

But now it gets complicated (at least I think so) ... if I _publish_ a module, I want Sinopia not to store it by itself, but to hand it over to the public npm registry. This also means that Sinopia has to authenticate against the official npm registry with my user.

In other words: I'd like to use Sinopia in the same way as [npm-proxy-cache](https://github.com/runk/npm-proxy-cache) works, but without the hassle to setup a proxy for npm.

Is it possible to use Sinopia in that way? If so, how do I have to configure it?

From looking at the `config.yaml` file and at the config file samples in [this repo](https://github.com/rlidwka/sinopia/tree/master/conf), unfortunately I was not able to figure this out by myself. Any hints?

**Comment by jdarling** [comment]
How about a private flag on the package.json that would tell sinopia not to push it to NPM, but if the flag wasn't there it would publish it to NPM?  Course allow defaults overrides in both directions would be idea since some of us use public, private (local), and private (corporate) NPM registries.

**Comment by rlidwka** [comment]
> How about a private flag on the package.json that would tell sinopia not to push it to NPM

How would you suggest for sinopia to push something to npm? I see two ways of doing that:

1. Sinopia could implement npm publishing protocol. This means that you have to write user:password for npm registry in sinopia config (insecure). Adding this functionality will also bring a maintenance burden, because sinopia would essentially be a full-featured npm client. Now sinopia can only read from npm registry, which is much easier.

2. Sinopia could be a dumb http proxy for publish requests. But this would mean that you'll have to use the same password with private registry and npm registry (very insecure). And it will also make a code more complex, because right now sinopia never works as an actual http proxy.

We tried the first option a year ago, didn't work out. Didn't try a second one, but I assume you can set up nginx to do this.

**Comment by jimongit** [comment]
one way you can do this is by using `npm cache <name>@version`, for example `npm cache camelcase@latest`. see the official [documentation](https://docs.npmjs.com/cli-commands/cache.html).
