### ISSUE TITLE
When package is removed in public should be removed in private

### ISSUE THREAD

**Issue by kodypeterson** [rlidwka/sinopia#219]
I have noticed that if a package update is added to the public registrty and then installed through sinopia it is now cached in sinopia. If the author removes it in the public registry it is not removed in the private registry and will still be served.

**Comment by rlidwka** [comment]
Nope, it very much shouldn't be.

Imagine a production application with shrinkwrapped dependencies being semi-automatically deployed onto a new server. If you use npm registry, and one of the packages was removed for whatever reason, the installation will fail. So sinopia is frequently used to prevent this kind of thing.

Why do you think it should be removed?

**Comment by kodypeterson** [comment]
So, think about this situation. Which we ran into:

- All our devs use our private repo.
- Bower has a dependency on the "rx" module.
- Someone installs bower locally and bower asks for the pacakge inquirer which needs rx "^2.2.27"
- It resolves to "2.4.8"
- Turns out "2.4.8" has a bug in it. The author pulls it out of the public registry

Now, every within the private org still gets "2.4.8" which contains a breaking bug blocking further development. The only current solution is to login to the box access the storage directory and delete the "rx" modules directory.

There has to be a better option.

**Comment by rlidwka** [comment]
> The only current solution is to login to the box access the storage directory and delete the "rx" modules directory.

Simpler solution might be to run `npm unpublish rx --reg https://sinopia.example.org/ --force`, so it will be removed from the cache (and re-added from npm registry later).

I agree that it's less than ideal though. Especially for the development tools.

Are any other modules getting unpublished for similar reasons? Because as I understand, the common practice in this case is to publish "2.4.9" with a bugfix shortly afterwards.

**Comment by kodypeterson** [comment]
True. Yeah, I am not so sure this is a common occurrence. We are just a very large development team using Sinopia as our source of NPM. It is working really well, but when our teams run into issues like this, I try to call them out and see what options are available. It would be great if there was an "admin" section of the web dashboard for Sinopia that could handle these sort of "maintenance" tasks.

What do you think about that? I could work on something and contribute it back.

**Comment by rlidwka** [comment]
> It would be great if there was an "admin" section of the web dashboard for Sinopia that could handle these sort of "maintenance" tasks.

I still hope most of those tasks can be solved by "npm" command-line tool. For example, "npm unpublish" I mentioned before.

So I'm not sure admin section fits here, because I want sinopia to be as simple as possible. Maybe we do need admin section, but I'd like to make sure we really need it first.

If you are a large company that needs an admin interface anyway, you could develop it as a separate project. I'll try to make the necessary api changes for such a tool to work.

**Comment by kodypeterson** [comment]
Well, alright then. Thanks for reaching out!

**Comment by cecton** [comment]
In my company we're looking for this behavior: packages that are deleted by the author are not removed from the private repo. I'm glad Sinopia does it so I can recommend it.

@rlidwka I think it would be worth mentioning it in the README (imho)

(Sorry for commenting on very old ticket)

**Comment by jmwilkinson** [comment]
@cecton This project is currently unmaintained. The good new is, there is a community fork: [verdaccio](https://www.verdaccio.org/).
