### ISSUE TITLE
How publish to uplink

### ISSUE THREAD

**Issue by thr0w** [rlidwka/sinopia#284]
Has some option to publish to npmjs (uplink)?
How to configure?
Thanks

**Comment by rlidwka** [comment]
If you're looking for a feature, so you publish a package to sinopia, and it re-publishes (proxies) your request to npmjs, then no. There is no such option right now. We used to have it, but it turned out to be too troublesome to maintain.

But you can publish stuff to npmjs directly (using `npm publish --reg https://registry.npmjs.org/` or `publishConfig`). Is it enough in your case?

**Comment by thr0w** [comment]
Yes @rlidwka, i'm looking for that feature.

--reg solve the problem but it's not pratical because need login every time I want swap server.

Thanks you. Best reggards!
